### ISSUE TITLE
Build prototype for GOES geostationary data viewer

### ISSUE THREAD

**Issue by Jeanne-le-Roux** [US-GHG-Center/custom-interfaces#120]
- [x] Skeleton React application for the Viewer.
- [x] Visualize the GOES sub-daily data from the STAC-api in a map environment.
  - [x] Add pointers in the map where the plumes are available.
  - [x] When zoomed in visualize the plumes. 
- [x] Add in Animation capability
- [x] Add in sidebar with metadata when the plume is clicked.
- [x] Add in search feature
- [x] Add in filter feature

**Comment by sanzog03** [comment]
We have a figma design worked out by @sandesh-sp. This design is intended for both emit and goes plume viewer.
[Link to figma Editor](https://www.figma.com/design/l1F72xSr5BlZ9zt34nJgwn/Emit?node-id=0-1&node-type=canvas&t=B0JfNju0yyNWMuxj-0)
[Link to figma prototype](https://www.figma.com/proto/l1F72xSr5BlZ9zt34nJgwn/Emit?node-id=1-2&node-type=canvas&t=B0JfNju0yyNWMuxj-0&scaling=contain&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=1%3A2)

**Comment by sanzog03** [comment]
Will be continuing on the prototype for further development in the follow-up tickets.
