### ISSUE TITLE
UI Improvements for EMIT

### ISSUE THREAD

**Issue by paridhi-parajuli** [US-GHG-Center/custom-interfaces#130]
Mock design by @sandesh-sp : https://www.figma.com/proto/l1F72xSr5BlZ9zt34nJgwn/Emit?page-id=0%3A1&node-id=1-2&node-type=canvas&viewport=-184%2C356%2C0.33&t=FkI5moRarkmCwfr1-1&scaling=contain&content-scaling=fixed&starting-point-node-id=1%3A2

- [x] Design toolbar
- [x] Design the plumes legend
- [x] Make the plumes legend better (as per the design given above)
- [x] Look for better options for the date selectors
- [x] Make the hamburger functionality consistent

**Comment by paridhi-parajuli** [comment]
[WIP] PR : https://github.com/US-GHG-Center/custom-interfaces/tree/update/UI

**Comment by paridhi-parajuli** [comment]
- Waiting for design changes decision for date selector
- Order plumes list by dates
- Add dots for data points to animation

**Comment by paridhi-parajuli** [comment]
Decided to go with the date slider instead of the date picker

**Comment by deborahUAH** [comment]
improved time series capability reviewed. Sharing with PO to get feedback on 11/22.   Feedback from PO meeting this week is the need to include intro text at top of viewer.  Text TBD

**Comment by paridhi-parajuli** [comment]
https://github.com/US-GHG-Center/custom-interfaces/pull/161
https://staging.earth.gov/ghgcenter/custom-interfaces/emit-ch4plume-v1
