### ISSUE TITLE
GOES plume viewer: UI updates to the GOES Plume viewer

### ISSUE THREAD

**Issue by sanzog03** [US-GHG-Center/custom-interfaces#135]
## Description
This is a follow up on task #120. The GOES methane plume viewer needs further UI work to be done. 

## Items to Address
- [x] Drawer not to overlap the mapbox controls.
- [x] Animation controls to be on par with the design mock.
- [x] Verify fonts and design consistency.

## Acceptance Criteria
- [x] UI on par with the design mockups.

## Additional Information
Link to Figma Design: [ref](https://www.figma.com/design/l1F72xSr5BlZ9zt34nJgwn/Emit?node-id=0-1&t=NSOEbPOBogGS3zcW-0)

## Related Issues/PRs
- #120

**Comment by taylordupre** [comment]
@amarouane-ABDELHAK Create CICD

**Comment by sanzog03** [comment]
latest changes are in staging: https://staging.earth.gov/ghgcenter/custom-interfaces/goes-plume-viewer
