### ISSUE TITLE
Update EMIT visualization to replace markers on certain zoom level

### ISSUE THREAD

**Issue by slesaad** [US-GHG-Center/custom-interfaces#22]
# Description
Based on the discussion here and a call with the EMIT team, we concluded that it's better to replace the marker with the outline of the plume at a certain zoom level.

And also add a disclaimer that the marker points to the area of max concentration rather than the "source" of the emission.

# Acceptance Criteria
- [x] The plume markers are replaced by the polygon outline at a certain zoom level
- [ ] The disclaimer is added

**Comment by amarouane-ABDELHAK** [comment]
Fix was merged to dev and eventually to staging and production. 
The new fix implements the described features:
- The map listens for the zoom event and toggles between displaying markers and a polygon outline based on the zoom level.
- Adds event listeners to the polygon outline to display a popup on hover, toggle raster visibility on click, and show/hide props div on click.
- Additionally, it shows the props div if the user clicks inside the polygon outline.
