### ISSUE TITLE
Fix EMIT visualization intermittent disappearance of markers

### ISSUE THREAD

**Issue by slesaad** [US-GHG-Center/custom-interfaces#24]
# Description
The EMIT visualization sometimes exhibits this issue where the map loads but the markers do not.

This issue is intermittent and there's no error logs.

Investigate and fix the issue.

# AC
- [x] The markers show up all the time

**Comment by amarouane-ABDELHAK** [comment]
The issue comes from an asynchronous problem where the map loaded before the markers were generated. A PR that implement a fix 
 is issued, and also we included a loading spinner in case marker generation takes a while.
