### ISSUE TITLE
Explore airborne data visualization for a single data

### ISSUE THREAD

**Issue by sanzog03** [US-GHG-Center/custom-interfaces#51]
Related to Epic [#242](https://github.com/US-GHG-Center/ghgc-architecture/issues/242)

Select one of the airborne data provided by NOAA and create a visualization for that.

Acceptance criteria:

- [x] Flight path is visualized.
- [x] There is a chart to visualize GHG concentration data with respect to flight path.

**Comment by sanzog03** [comment]
I have been working on implementing a prototype for the `FlightData_N57_20220828_RA.ict` nav and `NOAAPicarro-CO2-CH4-CO-H2O_N57_20220828_R0.ict` dataset.


![Image](https://github.com/US-GHG-Center/custom-interfaces/assets/38744044/e2cfb35b-37e0-48a2-81d0-11d703927e8f)

This is the initial implementation and needs additional work.
reference to repositories.

- Frontend application:  [https://github.com/sanzog03/fieldcampaign_frontend](https://github.com/sanzog03/fieldcampaign_frontend),
 		- branch: `main`
- Data Transformation: [https://github.com/sanzog03/fieldcampaign_data_transformation](https://github.com/sanzog03/fieldcampaign_data_transformation),
 		- branch: `custom-interfaces-51/noaa-field_campaign_exploration`

**Comment by Jeanne-le-Roux** [comment]
Thanks for getting a start on this!

fyi @deborahUAH

**Comment by sanzog03** [comment]
reference ticket @amarouane-ABDELHAK
