### ISSUE TITLE
Refactor airborne data visualization to support following upgrades

### ISSUE THREAD

**Issue by sanzog03** [US-GHG-Center/custom-interfaces#58]
Refactor the codebase to support future upgrades.

- [x] Integrate redux for state management.
- [x] Sync clock between map view and chart to enable rewind.
- [x] Explore consistency in the charts at varying clock speed.
- [x] Explore to visualize concentration spikes in the map view.

**Comment by sanzog03** [comment]
There is refactoring work done on the codebase along with some feature additions. The change log looks like the following:
[Preview link](http://ghgc-custom-interfaces-develop-airborne-visualization.s3-website-us-west-2.amazonaws.com/)

- Features:
	- Eager loading of the concentration data in addition to the previous interpolated chart data.
	    - ![image](https://github.com/user-attachments/assets/85658111-8cff-4ff1-a4ca-94f1e57864bf)
	    - ![image](https://github.com/user-attachments/assets/cfb6d69b-1ea8-47f4-bfd0-2c510957e6e5)
	- Resizable chart views.
	    - ![image](https://github.com/user-attachments/assets/a068ae32-78b1-44ff-98a8-ffe91b0f4520)
	    - ![image](https://github.com/user-attachments/assets/5ffc0904-b1b8-455c-8b78-4377d1a4396d)
	- Added controls to interact with the flight model, currently to track and un-track the aircraft.
	    - ![image](https://github.com/user-attachments/assets/2e8615d5-fbd4-4643-a65e-266b8966ceda)
	- Added red blob points on the map view when the concentration is above a defined (currently set to 420 ppm for co2) concentration measure.
	    - ![image](https://github.com/user-attachments/assets/4a8b43f0-3ede-4215-9280-97356a30c4de)
	    - ![image](https://github.com/user-attachments/assets/3c2afeae-b07b-4714-a1f9-41bd43e158a6)
- Improvements:
	- Redux for state management.
	- Add sync between map viewer and chart viewer with a reference header. The reference header (dotted line) in the chart moves with respect to the clock in the map. Note: we can rewind and forward the clock by either dragging the knob in the timeline or by manipulating it directly through the clock widget.
	    - ![image](https://github.com/user-attachments/assets/a404db0f-73de-4cac-880d-d68c78893f41)
	    - ![image](https://github.com/user-attachments/assets/501ce8a0-3bb2-46d3-becf-0d8b076da270)
- Fixes:
	- Add consistency in charts at varying clock speeds, i.e. line artifacts does not show up.
	- Orientation fix using VelocityOrientationProperty with respect to position property of flight entity when loaded through CZML to evaluate quaternion rotation on runtime.

**Comment by sanzog03** [comment]
@Jeanne-le-Roux @slesaad @amarouane-ABDELHAK 👆

**Comment by slesaad** [comment]
Great job @sanzog03 !!! It's looking awesome!

**Comment by Jeanne-le-Roux** [comment]
Closing since we don't anticipate using the viewer for R3. We can include it if there's time.
