### ISSUE TITLE
NIST Tower Data Embedded Visualization

### ISSUE THREAD

**Issue by Jeanne-le-Roux** [US-GHG-Center/custom-interfaces#69]
Ticket to create embedded visualization for NIST Tower data (urban testbed data) to go on the [dataset overview page](https://github.com/US-GHG-Center/ghgc-architecture/issues/321). 

Related tickets:
https://github.com/US-GHG-Center/ghgc-architecture/issues/301
https://github.com/US-GHG-Center/ghgc-architecture/issues/306
https://github.com/US-GHG-Center/ghgc-architecture/issues/305

**Comment by slesaad** [comment]
Duplicate of https://github.com/US-GHG-Center/ghgc-architecture/issues/317
