### ISSUE TITLE
Create Urban Dashboard interface for Vulcan and GRA2PES

### ISSUE THREAD

**Issue by anisbhsl** [US-GHG-Center/custom-interfaces#79]
## Description
Create custom interface for urban dashboard. Use this slides link for reference: https://docs.google.com/presentation/d/1MFceBUxnh7CmiaGrDjR9qFHghZhP4ez2-62i37J08xw/edit#slide=id.p

## AC
- [x] Urban dashboard mockup for Vulcan and GRA2PES

**Comment by anisbhsl** [comment]
Urban Dashboard 🚧 

Update:

- [ ] Added Vulcan and Gra2pes raster layer
- [ ] Created new layout ac to Figma design
- [ ] Minor UI changes (zoom controls, content placements, etc)

Screenshots: 

GRA2PES
![Screenshot 2024-08-29 at 11 42 37 AM](https://github.com/user-attachments/assets/cd8990b6-0919-44f8-8e4a-7ebc24894073)


![Screenshot 2024-08-29 at 11 43 12 AM](https://github.com/user-attachments/assets/32f365bf-a285-4195-ba9a-76cbad9a9561)

VULCAN

![Screenshot 2024-08-29 at 11 44 29 AM](https://github.com/user-attachments/assets/6a758dc2-ad74-4487-9906-2b2f3baa86ec)

![Screenshot 2024-08-29 at 11 44 58 AM](https://github.com/user-attachments/assets/86fba127-ea39-42d6-bf1e-905cc89d0efb)

**Comment by slesaad** [comment]
Follow up ticket - https://github.com/US-GHG-Center/custom-interfaces/issues/85
