### ISSUE TITLE
Populate Urban dashboard with real data

### ISSUE THREAD

**Issue by slesaad** [US-GHG-Center/custom-interfaces#85]
# Description
Last sprint, the urban dashboard was implemented based on the requirements provided. However, it is currently using placeholder data.

We received the data (some, maybe all?) this weekend.

This ticket involves populating the dashboard with the obtained data plus making any improvements to make the dashboard visually and experientially pleasing.

# AC
- [x] Urban dashboard is updated with real data
- [x] Urban dashboard is ready for release 🚀

**Comment by slesaad** [comment]
gra2pes sectoral data to be received end of next week

**Comment by anisbhsl** [comment]
gra2pes sectoral data received and updated in the dashboard!
